

const int baseThfChanceVLK = 20;

const int baseThfChanceSFB = 20;

const int baseThfChanceBAU = 25;

const int baseThfChanceSTT = 45;

const int baseThfChanceNOV = 50;

const int baseThfChanceORG = 45;

const int baseThfChanceSLD = 60;

const int baseThfChanceTPL = 65;

const int baseThfChanceGRD = 70;

const int baseThfChanceKDF = 70;

const int baseThfChanceKDW = 75;

const int baseThfChanceGUR = 90;

const int baseThfChanceEBR = 85;

const int baseThfChanceDMB = 120;

const int baseThfChanceNON = 20;

const string pickpocket_final = "(Dokonaj kradzie¿y kieszonkowej)";

const string dialog_pickpocket = "(Kradzie¿ kieszonkowa)";