META{
	MergeMode = TRUE;
};

const int theftdiff = 10;

const int thiefxp = 10;

const int baseThfChanceVLK = 40;

const int baseThfChanceSFB = 40;

const int baseThfChanceBAU = 40;

const int baseThfChanceSTT = 35;

const int baseThfChanceNOV = 30;

const int baseThfChanceORG = 35;

const int baseThfChanceSLD = 25;

const int baseThfChanceTPL = 20;

const int baseThfChanceGRD = 20;

const int baseThfChanceKDF = 10;

const int baseThfChanceKDW = 10;

const int baseThfChanceGUR = 10;

const int baseThfChanceEBR = 10;

const int baseThfChanceDMB = 5;

const int baseThfChanceNON = 45;

const int baseThfChanceBAB = 45;

const string pickpocket_final = "(Dokonaj kradzie¿y kieszonkowej)";

const string dialog_pickpocket = "(Kradzie¿ kieszonkowa)";