instance BAN_1601_Briam (Npc_Default)
{
	//Generated by Gothic NPC Maker

	//----------Info ogolne----------

	name 	= "Briam";
	Npctype = npctype_main;
	guild 	= GIL_BAU;
	level 	= 20;
	voice 	= 6;
	id 		= 1601;
    flags = NPC_FLAG_IMMORTAL;
	//----------Statystyki----------

	attribute[ATR_STRENGTH] = 120;
	attribute[ATR_DEXTERITY] = 60;
	attribute[ATR_MANA_MAX] = 60;
	attribute[ATR_MANA] = 60;
	attribute[ATR_HITPOINTS_MAX] = 520;
	attribute[ATR_HITPOINTS] = 520;

	//-------- visuals --------
	// 				animations
	Mdl_SetVisual		(self,"HUMANS.MDS");
	Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
	//	body mesh,	head mesh,	hairmesh,	face-tex,	hair-tex,	skin	
	Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_Fighter", 35,  2, BAU_ARMOR_H);
	
	B_Scale (self);	
	Mdl_SetModelFatness (self, 0);	

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_03);
EquipItem		(self, ItRw_Bow_Long_01);
CreateInvItems  (self,ItMiFlask                 ,10);
CreateInvItems  (self,ItMi_Alchemy_Alcohol_01    ,5);
CreateInvItems  (self,ItMi_Alchemy_Quicksilver_01,5);
CreateInvItems  (self,ItWr_AlchemyPermPotions1   ,1);
CreateInvItems  (self,ItWr_AlchemySprintPotions  ,1);
CreateInvItems  (self,ItMi_Alchemy_Sulphur_01   ,10);
CreateInvItems  (self,ItMi_Alchemy_Salt_01      ,10);
//----------Handlarz_aivar------
self.aivar[AIV_NPCISTRADER] = true;

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Ranged;
daily_routine = Rtn_start_1601;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_1601 ()
{
	TA_Sleep				(00,00,08,00,"LOCATION_11_11");
	TA_PotionAlchemy		(08,00,22,00,"BALCHEMY");
};