instance BAN_1605_Rocky (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name    = "Rocky";
Npctype = Npctype_Main;
guild   = GIL_BAU;
level   = 55;
voice   = 6;
id      = 1605;

//----------Statystyki----------

attribute[ATR_STRENGTH]      = 120;
attribute[ATR_DEXTERITY]     = 60;
attribute[ATR_MANA_MAX]      = 0;
attribute[ATR_MANA]          = 0;
attribute[ATR_HITPOINTS_MAX] = 560;
attribute[ATR_HITPOINTS]     = 560;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");

Mdl_SetVisualBody (self,"hum_body_Naked0",0, 2, "Hum_Head_FatBald", 130, 2, BAU_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Axe_Old_02);
EquipItem		(self, ItRw_Bow_Long_05_Z);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine   = Rtn_start_1605;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_1605 ()
{
TA_Sleep (01,10,07,35,"ROCKY_BED");
TA_skrzynka (07,35,09,00,"CHEST_BAU");
TA_Smith_Sharp (09,00,11,45,"OSELKA1");
TA_RepairHut (11,45,13,15,"ROCKY");
TA_PracticeSword (13,15,15,00,"BN_TRENING_WSZYSCY");
TA_Smoke (15,00,17,20,"LOCATION_11_12_01");
TA_Smith_Sharp (17,20,18,20,"OSELKA1");
TA_Smalltalk (18,20,21,20,"ROCKY");
TA_SitAround (21,20,01,10,"QUENTIN_SIT");
};
FUNC VOID Rtn_atak_1605 ()
{
TA_GuidePC (06,00,12,00,"ATAK009");
TA_GuidePC (12,00,16,40,"ATAK009");
TA_GuidePC (16,40,18,00,"ATAK009");
TA_GuidePC (18,00,06,00,"ATAK009");
};
FUNC VOID Rtn_atak2_1605 ()
{
TA_FollowPC (06,00,12,00,"ESKORTA1");
TA_FollowPC (12,00,16,40,"ESKORTA1");
TA_FollowPC (16,40,18,00,"ESKORTA1");
TA_FollowPC (18,00,06,00,"ESKORTA1");
};
FUNC VOID Rtn_ucieczka_1605 ()
{
TA_Stand (06,00,12,00,"OW_PATH_1_5_A");
TA_Stand (12,00,16,40,"OW_PATH_1_5_A");
TA_Stand (16,40,18,00,"OW_PATH_1_5_A");
TA_Stand (18,00,06,00,"OW_PATH_1_5_A");
};
FUNC VOID Rtn_mine_1605 ()
{
TA_Stand_Ignorance (06,00,12,00,"CAMP01");
TA_Stand_Ignorance (12,00,16,40,"CAMP01");
TA_Stand_Ignorance (16,40,18,00,"CAMP01");
TA_Stand_Ignorance (18,00,06,00,"CAMP01");
};
FUNC VOID Rtn_odb_1605 ()
{
TA_FollowPC (06,00,12,00,"OW_PATH_1_14");
TA_FollowPC (12,00,16,40,"OW_PATH_1_14");
TA_FollowPC (16,40,18,00,"OW_PATH_1_14");
TA_FollowPC (18,00,06,00,"OW_PATH_1_14");
};

FUNC VOID Rtn_TMQPTH_1605 ()
{
    TA_GuidePC (13,00,14,00,"PATH_OC_NC_14");	
    TA_GuidePC (14,00,13,00,"PATH_OC_NC_14");	
};

FUNC VOID Rtn_TMQPTHTWO_1605 ()
{
    TA_FollowPC (13,00,14,00,"PATH_OC_NC_14");	
    TA_FollowPC (14,00,13,00,"PATH_OC_NC_14");	
};

FUNC VOID Rtn_VICTOR_1605 ()
{
    TA_Stand (13,00,14,00,"WP_ZL_ROCKY");	
    TA_Stand (14,00,13,00,"WP_ZL_ROCKY");	
};