instance GRD_40050_Straznik (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = NAME_ConvoiWache;
Npctype = Npctype_Ambient;
guild = GIL_GOBBO; 
level = 20;
voice = 11;
id = 40050;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 75;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 300;
attribute[ATR_HITPOINTS] = 300;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",5, 0,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------
B_SetFightSkills(self,70);
//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Long_01);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_40050;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40050 ()
{
TA_GuardPatrol (18,00,06,00,"PACHOL3");
TA_GuardPatrol (06,00,18,00,"PACHOL3");
};

FUNC VOID Rtn_Konwoj_40050 ()	//FM
{
	TA_StandAround		(13,00,15,00,"OW_PATH_249");
	TA_StandAround		(15,00,24,00,"OW_PATH_249");
};
FUNC VOID Rtn_Konwoj2_40050 ()	//FM
{
	TA_StandAround		(13,00,15,00,"OW_PATH_254");
	TA_StandAround		(15,00,24,00,"OW_PATH_254");
};














