instance GRD_40104_Gardist (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = NAME_Gardist;
Npctype = Npctype_GUARD;
guild = GIL_GOBBO;
level = 20;
voice = 2;
id = 40104;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 280;
attribute[ATR_HITPOINTS] = 280;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",20, 0,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_04_Z);
//EquipItem		(self, ItRw_Crossbow_02);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;
daily_routine = Rtn_start_40104;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_Start_40104 ()
{
Ta_Guard (05,00,20,00, "WP_KH_CHEST"); 
TA_SitCampfire (20,00,05,00, "WP_KH_CHEST");
};
