instance GRD_40056_Winston (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Reflide
//----------Info ogolne----------

name = "Winston";
Npctype = Npctype_main;
guild = GIL_GRD;
level = 30;
voice = 7;
id = 40056;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 90;
attribute[ATR_DEXTERITY] = 70;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",2, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_New_05_Z);
EquipItem		(self, ItRw_Crossbow_02_Z);
B_CreateAmbientInv (self);     
CreateInvItems  (self,ItAmBolt,50);
//----------Pozostale----------
//edit by Nocturn
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40056;
//Generated by Gothic NPC MakerWP_WINSTON_2
};
FUNC VOID Rtn_start_40056 ()
{
TA_Boss (0,00,12,00,"WP_WINSTON_1");
TA_Boss (12,00,0,00,"WP_WINSTON_1");
};

FUNC VOID Rtn_rewanz_40056 ()
{
TA_Boss (0,00,12,00,"WP_WINSTON_2");
TA_Boss (12,00,0,00,"WP_WINSTON_2");
};

