//////////////////////////////////////////////////////
// HANDLARZ W OBOZIE MYŚLIWYCH
// SPECJALIZACJA: ALCHEMIA
//////////////////////////////////////////////////////

instance NON_5602_Stanley (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stanley";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 27;
voice = 11;
id = 5602;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 400;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_Psionic", 14,  1, NON_SHADOWBEAST_ARMOR);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,60);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1h_Sword_Bastard_01);
//EquipItem		(self, ItRw_Bow_Long_08);
CreateInvItems  (self,ItAt_Teeth_01,5);
CreateInvItems  (self,ItAt_Wolf_01,5);
CreateInvItems  (self,ItAt_Claws_01,5);
CreateInvItems  (self,ItArScrollLight,2);
CreateInvItems  (self,ItFoApple,5);
CreateInvItems  (self,ItFoLoaf,5);
CreateInvItems  (self,itmihammer,2);
CreateInvItems  (self,ItFoMutton,5);
CreateInvItems  (self,ItMi_Alchemy_Salt_01,25);
CreateInvItems  (self,ItMi_Alchemy_Zucker_01,25);
CreateInvItems  (self,ItMiNugget,220);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine = Rtn_start_5602;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_5602 ()
{
TA_Skrzynka (06,00,09,33,"SKRZYNIA");
TA_SitAround (09,33,12,10,"BENCH_MYS");
TA_Smoke (12,10,15,00,"POMOST8");
TA_PickRice (15,10,16,20,"ROBOTA");
TA_WorkMOB (16,20,18,25,"ROBOTA");
TA_SitAround (18,25,06,00,"BENCH_MYS");
};
FUNC VOID Rtn_gobliny_5602 ()
{
TA_GuidePC (06,00,09,33,"SPAWN_OW_BLACKGOBBO_A1");
TA_GuidePC (09,33,06,00,"SPAWN_OW_BLACKGOBBO_A1");
};

FUNC VOID Rtn_PNAW_5602 ()
{
TA_Lean (06,00,09,33,"WP_PNA_STANLEY_WAIT");
TA_Lean (09,33,06,00,"WP_PNA_STANLEY_WAIT");
};

FUNC VOID Rtn_PNAG_5602 ()
{
TA_FollowPc (06,00,09,33,"WP_PNA_STANLEY_WAIT");
TA_FollowPc (09,33,06,00,"WP_PNA_STANLEY_WAIT");
};