instance NON_40006_Przywodca (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Silny bandzior";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 15;
voice = 7;
id = 40006;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 65;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 220;
attribute[ATR_HITPOINTS] = 220;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",16, 1,ORG_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------WP_BDT_CORR3
B_SetFightSkills(self,50);
//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Sword_Long_03);
B_CreateAmbientInv (self);
CreateInvItems  (self,ItFo_Potion_Health_01,2);
CreateInvItems  (self,ItKeLockpick,1);
CreateInvItems  (self,ItWrMapCorristo_Copy,1);




//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40006;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40006 ()
{
TA_Smoke (00,00,12,00,"WP_BDT_CORR3");
TA_Smoke  (12,00,00,00,"WP_BDT_CORR3");
};
