instance NON_40008_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Bandzior";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 10;
voice = 6;
id = 40008;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 55;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 79,  1,STT_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,50);
//----------Ekwipunek----------
EquipItem		(self, ItMwZ_1H_Sword_01);
CreateInvItems  (self,ItAt_Teeth_01,3);
CreateInvItems  (self,ItForice,1);
CreateInvItems  (self,ItFoBooze,2);
CreateInvItems  (self,ItFo_Potion_Health_01,2);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40008;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40008 ()
{
TA_SitCampfire (00,00,12,00,"WP_BDT_CORR2");
TA_SitCampfire (12,00,00,00,"WP_BDT_CORR2");
};
