instance NON_40168_UndeadGardist (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn
//----------Info ogolne---------

name = "Nieumar³y gwardzista";
Npctype = Npctype_Main;
guild = GIL_ZOMBIE;
level = 45;

id = 40168;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 10;
attribute[ATR_MANA] = 10;
attribute[ATR_HITPOINTS_MAX] = 800;
attribute[ATR_HITPOINTS] = 800;

//----------Wyglad----------

    Mdl_SetVisual			(self,	"HumanS.mds");
	Mdl_ApplyOverlayMds 	(self,	"humans_1hST1.mds");
	Mdl_ApplyOverlayMds 	(self,	"humans_2hST2.mds");
	Mdl_ApplyOverlayMds 	(self,	"humans_BowT1.mds");
	Mdl_ApplyOverlayMds 	(self,	"humans_CBowT1.mds");
    B_SetNpcVisual 		    (self, MALE, "Ske_Head", 0, 0,HRODGIR_ARMOR_H);
    B_Scale (self);
    Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

B_SetFightSkills(self,90);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_New_05_Z);
EquipItem		(self, ItRw_Er_Crossbow_H02);
CreateInvItems  (self,ItMiNugget,30);
CreateInvItems  (self,ItMi_Stuff_OldCoin_01,50);
CreateInvItems  (self,ItMi_Black_Crystal_ABM,1);
CreateInvItems  (self,ItAmBolt,30);

senses						= SENSE_HEAR | SENSE_SEE | SENSE_SMELL;
senses_range				= 1000;

aivar[AIV_MM_Behaviour]			= HUNTER;
	
aivar[AIV_MM_PercRange]			= 1000;
aivar[AIV_MM_DrohRange]			= 1000;
aivar[AIV_MM_AttackRange]		= 1000;
aivar[AIV_MM_DrohTime]			= 0;
aivar[AIV_MM_FollowTime]		= 10;
aivar[AIV_MM_FollowInWater] 	= FALSE;
//----------Pozostale---------- //edit by Nocturn
fight_tactic	=	FAI_HUMAN_Master;
//daily_routine = Rtn_start_40168;

start_aistate				= ZS_MM_AllScheduler;

aivar[AIV_MM_RestStart] 	= OnlyRoutine;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40168 ()
{
TA_StayIgnoring (06,00,18,00,"VM_MAGE");
TA_StayIgnoring (18,00,06,00,"VM_MAGE");
};
