instance NON_40025_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Nowicjusz - rabuœ";
Npctype = Npctype_Main;
guild = GIL_BDT;
level = 15;
voice = 6;
id = 40025;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 55;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 79,  1,Nov_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,50);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_War_02);
CreateInvItems  (self,ItMi_Cadar_Crystal, 1);
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40025;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40025()
{
TA_SitCampfire (00,00,12,00,"WP_NOV_CADAR1");
TA_SitCampfire (12,00,00,00,"WP_NOV_CADAR1");
};
