instance NON_40009_Kastagir (Npc_Default)
{
//Generated by Gothic NPC Maker 

//----------Info ogolne----------

name = "Kastagir";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 70;
voice = 4;
id = 40009;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 145;
attribute[ATR_DEXTERITY] = 120;
attribute[ATR_MANA_MAX] 	= 400;
attribute[ATR_MANA] 		= 400;
attribute[ATR_HITPOINTS_MAX] =1050;
attribute[ATR_HITPOINTS] = 1050;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");

//							Body-Mesh			Body-Tex	Skin-Color	Head-MMS				Head-Tex	Teeth-Tex	Armor
	Mdl_SetVisualBody (self,	"hum_body_Naked0", 	0,			3,			"Hum_Head_Fighter", 	141,			0,			NON_ORCHUNTERARMOR_01);

B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

B_SetFightSkills(self,80);
//----------Ekwipunek----------
EquipItem		   (self, ItMw_2H_Axe_80);
B_CreateAmbientInv (self);
CreateInvItem (self, Plan_Miecz2H5);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;

daily_routine    = Rtn_start_40009;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40009 ()
{
TA_SitCampfire (06,00,24,35,"WP_KASTRAGIR");
TA_SitCampfire (24,35,06,00,"WP_KASTRAGIR");
};
FUNC VOID Rtn_cava_40009 ()
{
TA_Stand (08,00,15,25,"LOCATION_02_02");
TA_Stand (15,25,08,00,"LOCATION_02_02");
};
FUNC VOID Rtn_wait_40009 ()
{
TA_GuidePC (06,00,08,33,"WP_ADD_01");
TA_GuidePC (08,33,06,00,"WP_ADD_01");
};



