instance NON_40004_Przywodca (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Reflide

//----------Info ogolne----------

name = "Herszt bandy";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 20;
voice = 7;
id = 40004;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 220;
attribute[ATR_HITPOINTS] = 220;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",12, 1,GRD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,50);

//----------Ekwipunek----------
EquipItem		(self, ItMwZ_1H_Sword_01);
CreateInvItems  (self,ItAt_Teeth_01,3);
B_CreateAmbientInv (self);
CreateInvItems  (self,ItMi_Corristo_pack,1);
CreateInvItems  (self,ItMi_OrryTowary,1);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40004;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40004 ()
{
TA_Smoke (00,00,12,00,"WP_COR_RAB4");
TA_Smoke  (12,00,00,00,"WP_COR_RAB4");
};
