instance NON_40111_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Nocturn

//----------Info ogolne----------

name = "Nowicjusz - rabuœ";
Npctype = Npctype_Main;
guild = GIL_BDT;
level = 15;
voice = 7;
id = 40111;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 260;
attribute[ATR_HITPOINTS] = 260;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",14, 1,NOV_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,50);
//----------Ekwipunek----------
EquipItem		(self, ItMwZ_1H_Sword_01);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40111;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40111 ()
{
TA_SitAround (00,00,12,00,"WP_BG_B2");
TA_SitAround (12,00,00,00,"WP_BG_B2");
};
