instance NON_40073_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker
//edit by Reflide

//----------Info ogolne----------

name = "Szkodnik";
Npctype = Npctype_AMbient;
guild = GIL_ORG;
level = 10;
voice = 7;
id = 40073;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 50;
attribute[ATR_DEXTERITY] = 50;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 160;
attribute[ATR_HITPOINTS] = 160;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Bald",18, 1,ORG_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,50);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_03_Z);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_STRONG;
daily_routine = Rtn_start_40073;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40073 ()
{
TA_SitCampfire (00,00,12,00,"WP_LSZ_SZKODNICY");
TA_SitCampfire (12,00,00,00,"WP_LSZ_SZKODNICY");
};
