instance NON_40154_Torbeld (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Torbeld";
Npctype = Npctype_Main;
guild = GIL_NONE;
level = 55;
voice = 3;
id = 40154;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 120;
attribute[ATR_DEXTERITY] = 130;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 450;
attribute[ATR_HITPOINTS] = 400;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 1,"Hum_Head_Bald",153, 1,NON_ORCHUNTERARMOR_01);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_SCH);
EquipItem		(self, ItRw_Bow_War_02_Z);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;
daily_routine = Rtn_start_40154;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40154 ()
{
TA_Smoke (06,00,15,00,"LOCATION_02_05");
TA_Stand (15,00,16,33,"LOCATION_02_05");
TA_Boss (16,33,21,20,"LOCATION_02_05");
TA_SitCampfire (21,20,06,00,"LOCATION_02_05");
};
