instance NON_40083_Bandyta (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = NAME_Robuer;
Npctype = Npctype_ambient;
guild = GIL_ORCSCOUT;
level = 20;
voice = 7;
id = 40083;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 60;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 360;
attribute[ATR_HITPOINTS] = 360;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 0,"Hum_Head_Bald",100, 1,ORG_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_War_03_Z);
EquipItem		(self, ItRw_Bow_Long_02);
CreateInvItems (self, ItAmArrow,15);
B_CreateAmbientInv (self);
//----------Pozostale----------
B_SetFightSkills(self,50);
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine   = Rtn_start_40083;
//Generated by Gothic NPC Maker
};

FUNC VOID Rtn_start_40083 ()
{

    TA_SitAround (08,05,18,05,"WP_BANDYTA_WIEZA_ER1");
	TA_SitAround (18,05,08,05,"WP_BANDYTA_WIEZA_ER1");
};
