instance NON_40003_Rabus (Npc_Default)
{
//Generated by Gothic NPC Maker


//----------Info ogolne----------

name = "Szkodnik - rabuœ";
Npctype = Npctype_Main;
guild = GIL_ORG;
level = 10;
voice = 6;
id = 40003;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 55;
attribute[ATR_DEXTERITY] = 40;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 200;
attribute[ATR_HITPOINTS] = 200;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 0, 1,"Hum_Head_FatBald", 79,  1,ORG_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,50);
//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_War_02);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_MASTER;
daily_routine = Rtn_start_40003;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40003 ()
{
TA_SitCampfire (00,00,12,00,"WP_COR_RAB3");
TA_SitCampfire (12,00,00,00,"WP_COR_RAB3");
};
