instance NOV_40074_DeadNovize (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Martwy Nowicjusz";
Npctype = Npctype_Main;
guild = GIL_NOV;
level = 5;
voice = 3;
id = 40074;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 5;
attribute[ATR_DEXTERITY] = 5;
attribute[ATR_MANA_MAX] = 5;
attribute[ATR_MANA] = 5;
attribute[ATR_HITPOINTS_MAX] = 0;
attribute[ATR_HITPOINTS] = 0;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",0, 0,"Hum_Head_Psionic",15, 0,NOV_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,50);

//----------Ekwipunek----------
EquipItem		     (self, ItMw_1H_Axe_Old_01);
B_CreateAmbientInv   (self);
CreateInvItem        (self, ItWr_CaineToFritz);
CreateInvItem        (self,ItFo_Potion_Fritz01);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Coward;
daily_routine   = Rtn_start_40074;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40074 ()
{
TA_Stay (06,00,18,00,"WP_GRU_DEAD_NOV");
TA_Stay (18,00,06,00,"WP_GRU_DEAD_NOV");
};
