instance ORG_2704_Mazin (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Mazin";
Npctype = Npctype_Main;
guild   = GIL_ORG;
level   = 20;
voice   = 1;
id      = 2704;
	flags       =   NPC_FLAG_IMMORTAL;
//----------Statystyki----------

attribute[ATR_STRENGTH] = 60;
attribute[ATR_DEXTERITY] = 30;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX]  = 360;
attribute[ATR_HITPOINTS]      = 360;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Relaxed.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 3,"Hum_Head_Bald",1, 3,ORG_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------

B_SetFightSkills(self,50);

//----------Ekwipunek----------
EquipItem		(self, ItMw_1H_Mace_02);

CreateInvItems  (self,ItFoMuttonRaw   ,3);
CreateInvItems  (self,ItFosoup        ,2);
CreateInvItems  (self,ItMiNugget    ,100);
CreateInvItems  (self,ItKeLockpick   ,10);
CreateInvItems  (self,ItFoChesseSoup  ,5);
CreateInvItems  (self,ItFoBeer        ,5);
CreateInvItems  (self,ItFoWine        ,5);
CreateInvItems  (self,ItFoBooze       ,5);
CreateInvItems  (self,ItFoChesseSoup  ,5);
CreateInvItems  (self,JajoSca2        ,5);

//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Strong;
daily_routine   =   Rtn_start_2704;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_2704 ()
{
TA_Smoke (06,00,12,45,"KARCZMARZ2");
TA_Cook (12,45,18,00,"KARCZMARZ3");
TA_Stand (18,00,06,00,"KARCZMARZ2");
};
FUNC VOID Rtn_wpierdol_2704 ()
{
TA_Stay (06,00,18,00,"JAKASCUJNIA");
TA_Stay (18,00,06,00,"JAKASCUJNIA");
};
