instance SLD_40064_Fritz (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Fritz";
Npctype = Npctype_Main;
guild = GIL_SLD;
level = 40;
voice = 10;
id = 40064;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 125;
attribute[ATR_DEXTERITY] = 125;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 620;
attribute[ATR_HITPOINTS] = 620;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",2, 1,"Hum_Head_Pony",140, 0,SLD_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,1.5);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);
//----------Ekwipunek----------
EquipItem		(self, ItMw_1h_hammer_100);
EquipItem		(self, ItRw_Bow_War_02_Z);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_40064;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40064 ()
{
TA_SitAround     (06,00,8,30,"WP_NC_FRITZ");
TA_Smalltalk     (08,30,13,30,"WP_NC_FRITZ");
TA_PracticeSword (13,30,17,30,"WP_TRAIN_FRITZ");//with 2802
TA_Smoke         (17,30,24,45,"OW_PATH_073");
TA_SitAround     (24,45,06,00,"WP_NC_FRITZ");

};
FUNC VOID Rtn_GWM_40064()
{
TA_FollowPC (06,00,13,22,"WP_GWM_01");
TA_FollowPC (13,22,06,00,"WP_GWM_01");
};
FUNC VOID Rtn_GWMGRD_40064()
{
TA_FollowPC (06,00,13,22,"WP_GWM_01");
TA_FollowPC (13,22,06,00,"WP_GWM_01");
};
FUNC VOID Rtn_GWM2_40064()
{
TA_Guard (06,00,13,22,"WP_GWM_01");
TA_Guard (13,22,06,00,"WP_GWM_01");
};
FUNC VOID Rtn_GWM3_40064()
{
TA_Guard (06,00,13,22,"NC_KDW_CAVE_STAIRS");
TA_Guard (13,22,06,00,"NC_KDW_CAVE_STAIRS");
};