instance SLD_40070_Florian (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Florian";
Npctype = Npctype_Main;
guild = GIL_SLD;
level = 40;
voice = 10;
id = 40070;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 100;
attribute[ATR_DEXTERITY] = 100;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 500;
attribute[ATR_HITPOINTS] = 500;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Arrogance.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",0, 1,"Hum_Head_Bald", 137,  4,SLD_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,70);
//----------Ekwipunek----------
EquipItem		(self, ItMw_065_2h_greataxe_01);
EquipItem		(self, ItRw_Bow_War_02_Z);
B_CreateAmbientInv (self);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;
daily_routine = Rtn_start_40070;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40070 ()
{
TA_SitAround (06,00,13,22,"NC_TAVERN_SIT");
TA_SitAround (13,22,06,00,"NC_TAVERN_SIT");//with 2802


};
FUNC VOID Rtn_PZ_40070 ()
{
TA_Stand  (06,00,13,22,"NC_ENTRANCE_WP01");
TA_Stand (13,22,06,00,"NC_ENTRANCE_WP01");//with 2802


};
FUNC VOID Rtn_PZLee_40070 ()
{
TA_Smalltalk   	(07,00,19,00,"NC_SMALL_CAVE_CENTER");
	TA_Boss			(19,00,00,00,"NC_HUT05_OUT");
	TA_Sleep		(00,00,07,00,"NC_HUT05_IN");	

};
