instance TPL_40082_TempleGuard (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stra¿nik Œwi¹tynny";
Npctype = Npctype_Guard;
guild = GIL_TPL;
level = 40;
voice = 3;
id = 40082;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 95;
attribute[ATR_DEXTERITY] = 95;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 520;
attribute[ATR_HITPOINTS] = 520;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0", 1, 1 ,"Hum_Head_Psionic", 59 ,  2, TPL_ARMOR_M);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Umiejetnasci----------
B_SetFightSkills(self,80);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_Light_02);
EquipItem		(self, ItRw_Crossbow_02);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;
daily_routine = Rtn_start_40082;
//Generated by Gothic NPC Maker



};
FUNC VOID Rtn_start_40082 ()
{
    TA_Guard (08,05,18,05,"WP_BLO_TPL3");
	TA_Guard (18,05,08,05,"WP_BLO_TPL3");
};

FUNC VOID Rtn_Blokada_40082 ()
{
    TA_FollowPc (08,05,18,05,"WP_BLO_TPL1");
	TA_FollowPc	(18,05,08,05,"WP_BLO_TPL1");
};