instance TPL_40092_TempleGuard (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Stra¿nik Œwi¹tynny";
Npctype = Npctype_Guard;
guild = GIL_TPL;
level = 40;
voice = 8;
id = 40092;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 95;
attribute[ATR_DEXTERITY] = 95;
attribute[ATR_MANA_MAX] = 100;
attribute[ATR_MANA] = 100;
attribute[ATR_HITPOINTS_MAX] = 520;
attribute[ATR_HITPOINTS] = 520;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Militia.mds");
Mdl_SetVisualBody (self,"hum_body_naked0",1, 0,"Hum_Head_Psionic",15, 0,TPL_ARMOR_H);
B_Scale (self);
Mdl_SetModelFatness(self,1);

//----------Umiejetnasci----------

B_SetFightSkills(self,70);

//----------Ekwipunek----------
EquipItem		(self, ItMw_2H_Sword_Light_02);
EquipItem		(self, ItRw_Crossbow_02);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_Master;
daily_routine = Rtn_start_40092;
//Generated by Gothic NPC Maker

};
FUNC VOID Rtn_start_40092 ()
{

    TA_Guard (08,05,18,05,"WP_TPL_GUARD2");
	TA_Guard (18,05,08,05,"WP_TPL_GUARD2");
};
