instance VLK_40162_Buddler (Npc_Default)
{
//Generated by Gothic NPC Maker

//----------Info ogolne----------

name = "Kopacz";
Npctype = Npctype_Ambient;
guild = GIL_VLK;
level = 3;
voice = 1;
id = 40162;

//----------Statystyki----------

attribute[ATR_STRENGTH] = 12;
attribute[ATR_DEXTERITY] = 12;
attribute[ATR_MANA_MAX] = 0;
attribute[ATR_MANA] = 0;
attribute[ATR_HITPOINTS_MAX] = 60;
attribute[ATR_HITPOINTS] = 60;

//----------Wyglad----------

Mdl_SetVisual		(self,"HUMANS.MDS");
Mdl_ApplyOverlayMds	(self,"Humans_Tired.mds");
Mdl_SetVisualBody (self,"hum_body_Naked0",2,1,"Hum_Head_Bald", 68,  1, VLK_ARMOR_L);
B_Scale (self);
Mdl_SetModelFatness(self,0);

//----------Ekwipunek----------
EquipItem		(self, ItMwPickaxe);
B_SetFightSkills(self,10);
//----------Pozostale----------
fight_tactic	=	FAI_HUMAN_master;
daily_routine = Rtn_start_40162;
//Generated by Gothic NPC Maker
};
FUNC VOID Rtn_start_40162 ()
{
TA_SitCampfire (06,00,22,00,"OC_ROUND_22_CF_2_MOVEMENT");
TA_SitCampfire (22,00,06,00,"OC_ROUND_22_CF_2_MOVEMENT");
};
